# Generated by Django 3.2.19 on 2023-06-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perma', '0020_linkbatch_cached_capture_job_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalCourt',
            fields=[
            ],
            options={
                'verbose_name': 'Federal Court',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('perma.registrar',),
        ),
    ]
