# Generated by Django 3.2.19 on 2023-06-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0021_auto_20230629_1545'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalCourtOrganization',
            fields=[
            ],
            options={
                'verbose_name': 'Federal Court Organization',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('perma.organization',),
        ),
    ]
