web: gunicorn --log-level debug --access-logfile - -w 1 -b 0.0.0.0:$PORT -k gevent --forwarded-allow-ips '*' perma.wsgi
worker: celery -A perma worker --loglevel=info --concurrency=1 --without-gossip --without-mingle --without-heartbeat
beat: celery -A perma beat --loglevel=info
