# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mirror',
            name='content_url',
            field=models.URLField(help_text='E.g. https://mirror.example.edu:8080/', max_length=255),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='hostname',
            field=models.CharField(help_text='E.g. mirror.example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='ip',
            field=models.CharField(help_text='E.g. 12.34.56.78', max_length=15),
        ),
        migrations.AlterField(
            model_name='mirror',
            name='peer_port',
            field=models.IntegerField(default=9729, help_text='Port where this mirror listens for other LOCKSS nodes.'),
        ),
    ]
