# Generated by Django 4.2.8 on 2023-12-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lockss', '0002_auto_20180625_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mirror',
        ),
    ]
