INTERNAL = {
    'MINUTE_LIMIT': '60/m',
    'HOUR_LIMIT': '1000/h',
    'DAY_LIMIT': '5000/d',
    'REGISTER_MINUTE_LIMIT': '2/m',
    'REGISTER_HOUR_LIMIT': '10/h',
    'REGISTER_DAY_LIMIT': '50/d',
    'LOGIN_MINUTE_LIMIT': '5/m',
    'LOGIN_HOUR_LIMIT': '100/h',
    'LOGIN_DAY_LIMIT': '50/d',
}