# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='image_diff',
            field=models.ImageField(blank=True, null=True, upload_to='image_difss'),
        ),
    ]
