# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-13 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_compare_image_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='image_diff_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='image_diff_thumb'),
        ),
    ]
