from datetime import datetime
from datetime import timezone as tz

from django.conf import settings
from django.contrib.postgres.fields import DateTimeRangeField
from django.contrib.postgres.indexes import GistIndex
from django.db import IntegrityError, models, transaction
from django.db.models import Count, F, OuterRef, Q, Subquery, Sum
from django.db.models.functions import Coalesce
from django.template.defaultfilters import truncatechars
from django.urls import reverse
from django.utils import timezone
from model_utils import FieldTracker
from psycopg2.extras import DateTimeTZRange

from perma.utils import protocol, remove_control_characters


# Daily items with span at or before this range are excluded from backlog scheduling
# (early daily-item era, before the current pipeline): the upload producer starts at
# the oldest incomplete daily item after it.
DAILY_ITEM_BACKLOG_SPAN_FLOOR = ('2021-11-10', '2021-11-11')

# Links created after this date were only uploaded to daily IA items, not legacy per-link items.
LAST_INDIVIDUAL_LINK_IA_UPLOAD_DATE = '2022-10-03'

# Daily IA items Perma cannot edit on Internet Archive; skip uploads and confirmation tasks.
# We need IA's help to resolve the situation; once they transfer ownership of these items,
# we should be able to remove all references to this value.
UNEDITABLE_DAILY_ITEM_DATE_STRINGS = frozenset({
    '2022-07-19',
    '2022-07-20',
    '2022-07-21',
    '2022-07-25',
})


def uneditable_daily_item_identifiers():
    return [
        InternetArchiveItem.DAILY_IDENTIFIER.format(
            prefix=settings.INTERNET_ARCHIVE_DAILY_IDENTIFIER_PREFIX,
            date_string=date_string,
        )
        for date_string in sorted(UNEDITABLE_DAILY_ITEM_DATE_STRINGS)
    ]


def get_empty_datetime_range():
    return DateTimeTZRange(empty=True)


class InternetArchiveItem(models.Model):
    """
    Archive.org is made up of "items". An item is a logical "thing" that we represent on one web
    page on archive.org. An item can be considered as a group of files that deserve their own
    metadata.

    An item is just a directory of files and possibly subdirectories. Every item has at least two
    files, <identifier>_files.xml and <identifier>_meta.xml. The _meta.xml file is an XML file
    containing all of the metadata describing the item. The _files.xml file is an XML file
    containing all of the file-level metadata. There can only be one _meta.xml file and one
    _files.xml file per item. Alongside these metadata files and the original files uploaded to the
    item, the item may also contain derivative files automatically generated by archive.org.

    As a rule of thumb, items should:
    - not be over 100GB
    - not contain more than 10,000 files.

    (From documentation archived at https://perma.cc/S4WC-64AF)

    Expect one InternetArchiveItem object for every item in the perma_cc Internet Archive collection.
    """

    # Each item at Internet Archive has an identifier. An identifier is composed
    # of a unique combination of alphanumeric characters (limited to ASCII), underscores (_),
    # dashes (-), or periods (.). The first character of an identifier must be alphanumeric
    # (e.g. it cannot start out with an underscore, dash, or period). The maximum length of
    # an identifier is 100 characters, but we generally recommend that identifiers be between
    # 5 and 80 characters in length. Identifiers must be unique across the entirety of Internet
    # Archive, not simply unique within a single collection.
    # (From documentation archived at https://perma.cc/AVZ8-FD57)
    identifier = models.CharField(max_length=100, null=False, blank=False, primary_key=True, editable=False)
    confirmed_exists = models.BooleanField(
        default=False,
        db_index=True,
        help_text="If false we have attempted to create that item, but have not yet confirmed whether that attempt succeeded; failed attempts are not uncommon."
    )

    # The best available field reporting when an Item was added to Internet Archive.
    # (From documentation archived at https://perma.cc/U88M-6R5C)
    # If the item has been "darked" by IA (e.g. removed after a copyright or content complaint),
    # this field is no longer returned by the API, so may be unrecoverable.
    added_date = models.DateTimeField(null=True, blank=True)

    # InternetArchiveItem.objects.filter(span__isempty=True) were created for a single Perma Link
    # InternetArchiveItem.objects.filter(span__isempty=False) were created for all Perma Links created during this span of time
    # (https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/fields/#isempty)
    span = DateTimeRangeField(default=get_empty_datetime_range, help_text="The lower bound is included, and the upper bound excluded. That is, bounds='[)'")

    cached_is_dark = models.BooleanField(default=False, db_index=True)
    cached_file_count = models.IntegerField(null=True, blank=True, default=None)
    cached_title = models.TextField(null=True, blank=True, default=None)
    cached_description = models.TextField(null=True, blank=True, default=None)

    tasks_in_progress = models.IntegerField(default=0, db_index=True, help_text="We have asked Internet Archive to run appx this many tasks for this item and have not yet confirmed that those tasks are complete; derivative tasks not counted. Recomputed from file statuses by refresh_tasks_in_progress.")
    complete = models.BooleanField(default=False, help_text=(
        "Initial uploads complete: True when the upload producer found no eligible links for this "
        "daily item's day without an InternetArchiveFile, and no upload being attempted, once the "
        "day was more than three days past. The producer's day-by-day walk skips items marked True. "
        "It does not reflect later changes in links' eligibility, such as privacy changes."
    ))
    last_derived = models.DateTimeField(null=True, blank=True)
    derive_required = models.BooleanField(default=False)
    ia_creation_refused_at = models.DateTimeField(null=True, blank=True, help_text="When IA last refused to create this item, answering an upload as spam; cleared when IA accepts an upload to it. The upload producer sends only an occasional single upload to the item meanwhile.")
    ia_tasks_blocked_since = models.DateTimeField(null=True, blank=True, help_text="When a check first saw IA tasks for this item in error or paused, until a check sees none. The upload producer queues no uploads to the item meanwhile.")
    next_confirmation_check = models.DateTimeField(null=True, blank=True, help_text="Uploads to this item awaiting confirmation are not checked again before this time.")

    class Meta:
        verbose_name = "Internet Archive Item"

        indexes = [
            # We would like an index like the below, but expressions aren't supported in this version of Django.
            # We are adding it via a SQL migration instead. See 0007_auto_20221024_2049.py
            # models.Index(IsEmpty('span'), 'identifier', name='empty_span_idx'),
            GistIndex(fields=['span']),
            # the few items IA refused to create
            models.Index(
                fields=['ia_creation_refused_at'],
                condition=Q(ia_creation_refused_at__isnull=False),
                name='perma_iaitem_refused_idx',
            ),
            # the few items held back for IA tasks in error or paused
            models.Index(
                fields=['ia_tasks_blocked_since'],
                condition=Q(ia_tasks_blocked_since__isnull=False),
                name='perma_iaitem_blocked_idx',
            ),
        ]

    def __str__(self):
        return f"IA Item {self.identifier}"

    INDIVIDUAL_LINK_IDENTIFIER = '{prefix}{guid}'
    DAILY_IDENTIFIER = '{prefix}{date_string}'

    @classmethod
    def datetime(cls, datetime_string):
        return datetime.strptime(datetime_string, '%Y-%m-%d %H:%M:%S').replace(tzinfo=tz.utc)

    @classmethod
    def standard_metadata_for_date(cls, date_string):
        metadata = {
            "collection": settings.INTERNET_ARCHIVE_COLLECTION,
            "contributor": "Perma.cc",
            "mediatype": "web",
            "date": date_string,
            "title": f"{date_string} Perma.cc Captures",
            "description": f"Captures by Perma.cc from {date_string} (one WARC file and XML metadata file per webpage)",
        }
        return metadata

    @classmethod
    def inflight_task_count(cls):
        # The filter lets Postgres read only the few items with tasks from the
        # index on tasks_in_progress, which refresh_tasks_in_progress keeps >= 0.
        return cls.objects.filter(tasks_in_progress__gt=0).aggregate(Sum('tasks_in_progress'))['tasks_in_progress__sum']

    @classmethod
    def refresh_tasks_in_progress(cls, identifier=None):
        """
        Set tasks_in_progress to the number of this item's files that are in flight
        (see InternetArchiveFile.in_flight), for every item whose count is nonzero
        or should be, or for the one item named.
        """
        in_flight = InternetArchiveFile.in_flight()
        count = in_flight.filter(
            item_id=OuterRef('identifier')
        ).order_by().values('item_id').annotate(n=Count('*')).values('n')
        if identifier:
            identifiers = [identifier]
        else:
            # Two index lookups: combined into one filter with OR, or written as
            # "tasks_in_progress != 0", this reads the whole item table, most of
            # which is legacy single-link items.
            identifiers = set(
                cls.objects.filter(
                    Q(tasks_in_progress__gt=0) | Q(tasks_in_progress__lt=0)
                ).values_list('identifier', flat=True)
            ) | set(
                in_flight.values_list('item_id', flat=True).distinct()
            )
        cls.objects.filter(identifier__in=identifiers).update(tasks_in_progress=Coalesce(Subquery(count), 0))


class InternetArchiveFile(models.Model):
    """
    A file we uploaded to an Internet Archive "Item".

    Items may contain IA-produced, derivative files as well; for instance, cdx files.
    We do not store objects referencing those derivative files, only original files that we ourselves upload.
    """
    link = models.ForeignKey("Link", on_delete=models.DO_NOTHING, related_name='internet_archive_files')
    item = models.ForeignKey("InternetArchiveItem", on_delete=models.CASCADE, related_name='internet_archive_files')

    # Statuses that end the pipeline's work on a file and need a human:
    # - upload_unconfirmed: IA accepted the upload, but the file did not appear with the
    #   expected metadata within INTERNET_ARCHIVE_UPLOAD_CONFIRMATION_MAX_AGE, so we
    #   stopped checking.
    # - deletion_unconfirmed: IA accepted the deletion, but the file was still listed
    #   INTERNET_ARCHIVE_DELETION_CONFIRMATION_MAX_AGE later, so we stopped checking.
    # - upload_failed, deletion_failed: INTERNET_ARCHIVE_MAX_ATTEMPTS_PER_FILE attempts
    #   ended without a result, so we stopped trying.
    status = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        choices=((s, s) for s in ('upload_attempted', 'upload_submitted', 'upload_unconfirmed', 'upload_failed', 'confirmed_present', 'deletion_attempted', 'deletion_submitted', 'deletion_unconfirmed', 'deletion_failed', 'confirmed_absent')),
        db_index=True,
    )
    status_updated = models.DateTimeField(null=True, blank=True, help_text="When status was last saved, even if unchanged: an upload retry saves 'upload_attempted' again.")
    claim = models.CharField(max_length=255, null=True, blank=True, help_text="Identifies the task attempting the current upload or deletion: the id of the task message that started it.")
    attempts = models.IntegerField(default=0, db_default=0, help_text="How many times the current upload or deletion has been started: 1 when it begins, plus 1 each time it is taken up again after going stale. A task's own retries are not counted.")

    cached_size = models.IntegerField(null=True, blank=True, default=None)

    # Standard metadata fields, defined at https://archive.org/services/docs/api/metadata-schema/index.html#file-metadata-schema
    cached_title = models.TextField(null=True, blank=True, default=None)
    cached_comments = models.TextField(null=True, blank=True, default=None)
    cached_external_identifier = models.TextField(null=True, blank=True, default=None)
    cached_external_identifier_match_date = models.TextField(null=True, blank=True, default=None)
    cached_format = models.TextField(null=True, blank=True, default=None)

    # Custom metadata fields
    cached_submitted_url = models.TextField(null=True, blank=True, default=None)
    cached_perma_url = models.TextField(null=True, blank=True, default=None)

    tracker = FieldTracker()

    class Meta:
        verbose_name = "Internet Archive File"
        unique_together = (("link", "item"),)
        indexes = [
            # For in_flight(), per item and overall: a small index, since nearly
            # all files are 'confirmed_present'.
            models.Index(
                fields=['item', 'status_updated'],
                condition=Q(status__in=['upload_attempted', 'upload_submitted', 'deletion_attempted', 'deletion_submitted']),
                name='perma_iafile_in_flight_idx',
            ),
        ]

    def __str__(self):
        return f"IA File {self.pk}: {self.item_id} > {self.link_id}"

    def save(self, *args, **kwargs):
        update_fields = kwargs.get('update_fields')
        if update_fields is None or 'status' in update_fields:
            self.status_updated = timezone.now()
            if update_fields is not None:
                kwargs['update_fields'] = [*update_fields, 'status_updated']
        super().save(*args, **kwargs)

    @classmethod
    def in_flight(cls):
        """
        Files with an IA task we started and have not seen finish. An upload or
        deletion attempt that has not been saved again within
        INTERNET_ARCHIVE_ATTEMPT_STALE_AFTER belongs to a task that was killed or
        gave up, and is not counted.
        """
        stale_before = timezone.now() - settings.INTERNET_ARCHIVE_ATTEMPT_STALE_AFTER
        return cls.objects.filter(
            Q(status__in=['upload_submitted', 'deletion_submitted']) |
            Q(status__in=['upload_attempted', 'deletion_attempted'], status_updated__gte=stale_before)
        )

    @classmethod
    def stale_attempt(cls, status='upload_attempted'):
        """
        A Q matching upload (or deletion) attempts that are not in flight: not saved
        again within INTERNET_ARCHIVE_ATTEMPT_STALE_AFTER, or saved before
        status_updated was recorded at all. Their tasks were killed, gave up, or
        were lost from the queue.
        """
        stale_before = timezone.now() - settings.INTERNET_ARCHIVE_ATTEMPT_STALE_AFTER
        return Q(status=status) & (
            Q(status_updated__lt=stale_before) | Q(status_updated__isnull=True)
        )

    @classmethod
    def retryable_stale_attempt(cls, status='upload_attempted'):
        """
        A stale attempt that should be queued again: one started fewer than
        INTERNET_ARCHIVE_MAX_ATTEMPTS_PER_FILE times.
        """
        return cls.stale_attempt(status) & Q(attempts__lt=settings.INTERNET_ARCHIVE_MAX_ATTEMPTS_PER_FILE)

    # What a claim did (see claim_upload)
    CLAIM_NEW = 'new'
    CLAIM_RESUMED = 'resumed'
    CLAIM_STALE = 'stale'

    @classmethod
    def _claim(cls, item_id, link_id, attempting, starting_from, claim):
        """
        Claim an existing file for the attempt identified by `claim`: resume it if
        the file is already `attempting` under that claim, start a new attempt if
        the file is in one of the `starting_from` statuses, or take up a stale
        `attempting` attempt. Each step is one conditional UPDATE, so two callers
        cannot both succeed. Returns CLAIM_RESUMED, CLAIM_NEW, CLAIM_STALE or None.
        """
        if not claim:
            raise ValueError("A claim is required.")
        file = cls.objects.filter(item_id=item_id, link_id=link_id)
        now = timezone.now()
        if file.filter(status=attempting, claim=claim).update(status_updated=now):
            return cls.CLAIM_RESUMED
        if file.filter(status__in=starting_from).update(status=attempting, status_updated=now, claim=claim, attempts=1):
            return cls.CLAIM_NEW
        if file.filter(cls.stale_attempt(attempting)).update(status=attempting, status_updated=now, claim=claim, attempts=F('attempts') + 1):
            return cls.CLAIM_STALE
        return None

    @classmethod
    def claim_upload(cls, item_id, link_id, claim):
        """
        Mark this link's file in this item 'upload_attempted' for the calling task,
        unless another task holds the attempt. Returns what the claim did (see
        _claim), or None if the upload is not the caller's to attempt.

        `claim` identifies the attempt: the id of the task message that started it,
        which the task's own retries carry in a message header. A message that is
        delivered again after its worker stopped keeps its id, so it resumes its
        attempt too. Any task may start a new attempt on a file that does not exist
        yet or was deleted from IA, or take up a stale one; no other task may claim
        an attempt in progress.
        """
        try:
            with transaction.atomic():
                cls.objects.create(item_id=item_id, link_id=link_id, status='upload_attempted', claim=claim, attempts=1)
            return cls.CLAIM_NEW
        except IntegrityError:
            pass
        return cls._claim(item_id, link_id, 'upload_attempted', ['confirmed_absent'], claim)

    @classmethod
    def claim_deletion(cls, item_id, link_id, claim):
        """
        The deletion counterpart of claim_upload: mark the file 'deletion_attempted'
        for the attempt `claim` if it is 'confirmed_present', its deletion attempt is
        stale, or it is already that attempt's.
        """
        return cls._claim(item_id, link_id, 'deletion_attempted', ['confirmed_present'], claim)

    WARC_FILENAME = '{guid}.warc.gz'

    @classmethod
    def guid_from_filename(cls, filename):
        return filename.split('.')[0]

    @classmethod
    def standard_metadata_for_link(cls, link):
        title = f"{link.guid}: {truncatechars(link.submitted_title, 50)}"
        url = remove_control_characters(link.submitted_url)
        return {
            "title": title,
            "comments": f"Perma.cc archive of {url} created on {link.creation_timestamp}.",
            "external-identifier": f"urn:X-perma:{link.guid}",
            "external-identifier-match-date": f"X-perma:{link.creation_timestamp.isoformat()}",
            "format": "Web ARChive GZ",
            "submitted_url": url,
            "perma_url": protocol() + settings.HOST + reverse('single_permalink', args=[link.guid]),
        }

    def update_from_ia_metadata(self, metadata):
        """
        Intentionally does not call save(), so this method can be used with bulk database operations.
        """
        self.cached_title = metadata['title']
        self.cached_comments = metadata['comments']
        self.cached_external_identifier = metadata['external-identifier']
        self.cached_external_identifier_match_date = metadata['external-identifier-match-date']
        self.cached_format = metadata['format']
        self.cached_submitted_url = metadata['submitted_url']
        self.cached_perma_url = metadata['perma_url']

    def zero_cached_ia_metadata(self):
        """
        Intentionally does not call save(), so this method can be used with bulk database operations.
        """
        self.cached_title = None
        self.cached_comments = None
        self.cached_external_identifier = None
        self.cached_external_identifier_match_date = None
        self.cached_format = None
        self.cached_submitted_url = None
        self.cached_perma_url = None

