# Generated by Django 2.2.26 on 2022-01-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0001_squashed_0068_auto_20210525_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturejob',
            name='order',
            field=models.FloatField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['creation_timestamp'], name='perma_link_creatio_be33de_idx'),
        ),
    ]
