# Generated by Django 2.2.26 on 2022-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0002_auto_20220119_2034'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['submitted_url_surt'], name='perma_link_submitt_5959e7_idx'),
        ),
    ]
