# Generated by Django 2.2.28 on 2022-07-20 20:33

from django.db import migrations, models
import perma.models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0003_auto_20220120_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=perma.models.logo_file_path),
        ),
        migrations.AddIndex(
            model_name='capturejob',
            index=models.Index(fields=['human', 'order'], name='perma_captu_human_6e7428_idx'),
        ),
    ]
