# Generated by Django 2.2.28 on 2022-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0004_auto_20220721_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='internet_archive_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='internet_archive_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicallink',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('failed', 'failed'), ('deletion_incomplete', 'deletion_incomplete'), ('deletion_required', 'deletion_required'), ('deleted', 'deleted'), ('upload_or_reupload_required', 'upload_or_reupload_required'), ('derive_required', 'derive_required'), ('completed', 'completed')], db_index=True, default='not_started', max_length=28),
        ),
        migrations.AlterField(
            model_name='link',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('failed', 'failed'), ('deletion_incomplete', 'deletion_incomplete'), ('deletion_required', 'deletion_required'), ('deleted', 'deleted'), ('upload_or_reupload_required', 'upload_or_reupload_required'), ('derive_required', 'derive_required'), ('completed', 'completed')], db_index=True, default='not_started', max_length=28),
        ),
    ]
