# Generated by Django 2.2.28 on 2022-10-13 21:50

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import perma.models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0004_auto_20220721_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetArchiveItem',
            fields=[
                ('identifier', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
                ('span', django.contrib.postgres.fields.ranges.DateTimeRangeField(default=perma.models.get_empty_datetime_range, help_text="The lower bound is included, and the upper bound excluded. That is, bounds='[)'")),
                ('cached_file_count', models.IntegerField(blank=True, default=None, null=True)),
                ('cached_title', models.TextField(blank=True, default=None, null=True)),
                ('cached_description', models.TextField(blank=True, default=None, null=True)),
                ('complete', models.BooleanField(default=False, help_text='Has all the files it ought to have; has no files it ought not have.')),
                ('last_derived', models.DateTimeField(blank=True, null=True)),
                ('derive_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Internet Archive Item',
            },
        ),
        migrations.CreateModel(
            name='InternetArchiveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_size', models.IntegerField(blank=True, default=None, null=True)),
                ('cached_title', models.TextField(blank=True, default=None, null=True)),
                ('cached_comments', models.TextField(blank=True, default=None, null=True)),
                ('cached_external_identifier', models.TextField(blank=True, default=None, null=True)),
                ('cached_external_identifier_match_date', models.TextField(blank=True, default=None, null=True)),
                ('cached_format', models.TextField(blank=True, default=None, null=True)),
                ('cached_submitted_url', models.TextField(blank=True, default=None, null=True)),
                ('cached_perma_url', models.TextField(blank=True, default=None, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perma.InternetArchiveItem')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='perma.Link')),
            ],
            options={
                'verbose_name': 'Internet Archive File',
                'unique_together': {('link', 'item')},
            },
        ),
        migrations.AddField(
            model_name='link',
            name='internet_archive_items',
            field=models.ManyToManyField(related_name='links', through='perma.InternetArchiveFile', to='perma.InternetArchiveItem'),
        ),
    ]
