# Generated by Django 2.2.28 on 2022-08-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0005_derive_required_20220805_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='internet_archive_identifier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='internet_archive_identifier',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
