# Generated by Django 2.2.28 on 2022-10-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0005_auto_20221013_2150'),
        ('perma', '0005_auto_20221003_2033'),
    ]

    operations = [
    ]
