# Generated by Django 2.2.28 on 2022-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0005_auto_20221013_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='cached_path',
            field=models.TextField(),
        ),
    ]
