# Generated by Django 2.2.28 on 2022-10-24 20:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0006_auto_20221024_1521'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='internetarchiveitem',
            index=django.contrib.postgres.indexes.GistIndex(fields=['span'], name='perma_inter_span_bafa26_gist'),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "empty_span_idx" ON "perma_internetarchiveitem" ("identifier", (isempty("span")));',
            reverse_sql='DROP INDEX IF EXISTS "empty_span_idx";'
        ),
    ]
