# Generated by Django 2.2.28 on 2022-10-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0006_auto_20221024_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='default_to_screenshot_view',
            field=models.BooleanField(default=False, help_text='User defaults to screenshot view.'),
        ),
        migrations.AddField(
            model_name='link',
            name='default_to_screenshot_view',
            field=models.BooleanField(default=False, help_text='User defaults to screenshot view.'),
        ),
    ]
