# Generated by Django 2.2.28 on 2022-10-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0006_auto_20221024_1521'),
        ('perma', '0006_merge_20221024_1555'),
    ]

    operations = [
    ]
