# Generated by Django 2.2.28 on 2022-10-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0007_auto_20221024_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetarchivefile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internet_archive_files', to='perma.InternetArchiveItem'),
        ),
        migrations.AlterField(
            model_name='internetarchivefile',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='internet_archive_files', to='perma.Link'),
        ),
    ]
