# Generated by Django 2.2.28 on 2022-10-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0008_auto_20221027_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetarchivefile',
            name='status',
            field=models.CharField(blank=True, choices=[('upload_attempted', 'upload_attempted'), ('confirmed_present', 'confirmed_present'), ('deletion_attempted', 'deletion_attempted'), ('confirmed_absent', 'confirmed_absent')], db_index=True, max_length=19, null=True),
        ),
    ]
