# Generated by Django 2.2.28 on 2022-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0009_internetarchivefile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetarchiveitem',
            name='cached_is_dark',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
