# Generated by Django 2.2.28 on 2022-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0010_internetarchiveitem_cached_is_dark'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='default_to_screenshot_view',
            field=models.BooleanField(default=False, help_text='User defaults to screenshot view.'),
        ),
        migrations.AddField(
            model_name='link',
            name='default_to_screenshot_view',
            field=models.BooleanField(default=False, help_text='User defaults to screenshot view.'),
        ),
    ]
