# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='monthly_link_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='monthly_link_limit',
            field=models.IntegerField(default=10),
        ),
    ]
