# Generated by Django 2.2.28 on 2022-12-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0011_auto_20221117_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetarchiveitem',
            name='tasks_in_progress',
            field=models.IntegerField(default=0, help_text='We have asked Internet Archive to run appx this many tasks for this item and have not yet confirmed that those tasks are complete; derivative tasks not counted.'),
        ),
    ]
