# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('perma', '0012_auto_20160728_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='replacement_link',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='perma.Link'),
        ),
        migrations.AddField(
            model_name='link',
            name='replacement_link',
            field=models.ForeignKey(blank=True, help_text=b'New link to which readers should be forwarded when trying to view this link.', null=True, on_delete=django.db.models.deletion.CASCADE, to='perma.Link'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
