# Generated by Django 2.2.28 on 2023-02-14 16:15

from django.db import migrations, models


def populate_confirmed_exists(apps, schema_editor):
    """
    All the InternetArchiveItem objects currently in the database have been
    confirmed to exist. Set this field True for them now. New objects default
    to False, and are set to True when confirmed.
    """
    InternetArchiveItem = apps.get_model('perma', 'InternetArchiveItem')
    InternetArchiveItem.objects.all().update(confirmed_exists=True)


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0012_internetarchiveitem_tasks_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetarchiveitem',
            name='confirmed_exists',
            field=models.BooleanField(db_index=True, default=False, help_text='If false we have attempted to create that item, but have not yet confirmed whether that attempt succeeded; failed attempts are not uncommon.'),
        ),
        migrations.RunPython(populate_confirmed_exists),
    ]
