# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0013_auto_20160829_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='order',
            field=models.FloatField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capturejob',
            name='status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'in_progress', b'in_progress'), (b'completed', b'completed'), (b'deleted', b'deleted'), (b'failed', b'failed')], db_index=True, default=b'pending', max_length=15),
        ),
    ]
