# Generated by Django 2.2.28 on 2023-02-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0013_internetarchiveitem_confirmed_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetarchivefile',
            name='status',
            field=models.CharField(blank=True, choices=[('upload_attempted', 'upload_attempted'), ('upload_submitted', 'upload_submitted'), ('confirmed_present', 'confirmed_present'), ('deletion_attempted', 'deletion_attempted'), ('deletion_submitted', 'deletion_submitted'), ('confirmed_absent', 'confirmed_absent')], db_index=True, max_length=19, null=True),
        ),
    ]
