# Generated by Django 3.2.18 on 2023-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0014_auto_20230214_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetarchiveitem',
            name='tasks_in_progress',
            field=models.IntegerField(db_index=True, default=0, help_text='We have asked Internet Archive to run appx this many tasks for this item and have not yet confirmed that those tasks are complete; derivative tasks not counted.'),
        ),
    ]
