# Generated by Django 3.2.18 on 2023-04-03 22:02

import django.contrib.postgres.indexes
from django.db import migrations
import django.db.models.functions.text

from django.contrib.postgres.operations import (
    BtreeGinExtension,
    TrigramExtension,
)


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0015_alter_internetarchiveitem_tasks_in_progress'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='link',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('guid'), name='gin_trgm_ops'), name='guid_case_insensitive_idx'),
        ),
    ]
