# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0015_auto_20160929_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
