# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0015_auto_20160929_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uncaughterror',
            name='custom_message',
        ),
        migrations.RemoveField(
            model_name='uncaughterror',
            name='name',
        ),
        migrations.AlterField(
            model_name='uncaughterror',
            name='current_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uncaughterror',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uncaughterror',
            name='stack',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uncaughterror',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
