# Generated by Django 3.2.18 on 2023-04-04 19:24

from django.db import migrations
from django.db.models import Max, OuterRef, Subquery

def backfill_last_login(apps, schema_editor):
    LinkUser = apps.get_model('perma', 'LinkUser')
    AccessLog = apps.get_model('axes', 'AccessLog')

    print(f"Start: {LinkUser.objects.filter(last_login__isnull=True).count()} users with no last_login.")
    updated = LinkUser.objects.filter(
        is_confirmed=True
    ).exclude(
        last_login__gt='2023-04-03'
    ).update(
        last_login=Subquery (
            AccessLog.objects.filter(
                username=OuterRef('email')
            ).values_list('attempt_time', flat=True).order_by('-attempt_time')[:1]
        )
    )
    print(f"Updated last_login for {updated} users.")
    print(f"End: {LinkUser.objects.filter(last_login__isnull=True).count()} users with no last_login.")


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0016_link_guid_case_insensitive_idx'),
        ('axes', '0007_alter_accessattempt_unique_together'),
    ]

    operations = [
        migrations.RunPython(backfill_last_login, migrations.RunPython.noop, elidable=True),
    ]
