# Generated by Django 3.2.18 on 2023-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0017_auto_20230404_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='raw_email',
            field=models.CharField(max_length=255, null=True, verbose_name='raw email address'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='raw_email',
            field=models.CharField(max_length=255, null=True, verbose_name='raw email address'),
        ),
        migrations.RunSQL(
            sql='UPDATE perma_linkuser SET raw_email = email;',
            reverse_sql='UPDATE perma_linkuser SET email = raw_email;',
            elidable=True
        ),
        migrations.RunSQL(
            sql='UPDATE perma_linkuser SET email = LOWER(email);',
            reverse_sql=migrations.RunSQL.noop,
            elidable=True
        ),
    ]
