# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0017_rename_mylinks_to_personallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallink',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='link',
            name='view_count',
        ),
    ]
