# Generated by Django 3.2.18 on 2023-04-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0018_auto_20230424_1836'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX IF NOT EXISTS idx_lower_email_unique ON perma_linkuser (LOWER(email));',
            reverse_sql='DROP INDEX IF EXISTS idx_lower_email_unique;',
        ),
    ]
