# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-24 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0018_auto_20161130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text=b'If set, this user is an org user. This should not be set if registrar is set!<br><br>Note: <b>This list will include deleted orgs of which this user is a member.</b> This is a historical record and deleted org memberships cannot be removed.<br><br>', related_name='users', to='perma.Organization'),
        ),
    ]
