# Generated by Django 3.2.19 on 2023-05-25 19:08

from django.db import migrations, models

from django.db.models import OuterRef, Subquery, Count

def backfill_cached_capture_job_count(apps, schema_editor):
    LinkBatch = apps.get_model('perma', 'LinkBatch')
    CaptureJob = apps.get_model('perma', 'CaptureJob')

    print("Start backfilling capture job counts.")
    LinkBatch.objects.filter(
        cached_capture_job_count=0
    ).exclude(
        capture_jobs=None
    ).update(
        cached_capture_job_count=Subquery(
            CaptureJob.objects.filter(
                link_batch_id=OuterRef('id')
            ).values(
                'link_batch_id'
            ).annotate(
                count=Count('link_batch_id')
            ).values(
                'count'
            )
        )
    )
    print("Updated capture job counts")


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0019_auto_20230424_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkbatch',
            name='cached_capture_job_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_cached_capture_job_count, migrations.RunPython.noop, elidable=True),
    ]
