# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0019_auto_20170224_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallink',
            name='private_reason',
            field=models.CharField(blank=True, choices=[(b'policy', b'Robots.txt or meta tag'), (b'user', b'At user direction'), (b'takedown', b'At request of content owner'), (b'failure', b'Analysis of meta tags failed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='private_reason',
            field=models.CharField(blank=True, choices=[(b'policy', b'Robots.txt or meta tag'), (b'user', b'At user direction'), (b'takedown', b'At request of content owner'), (b'failure', b'Analysis of meta tags failed')], max_length=10, null=True),
        ),
    ]
