# Generated by Django 3.2.19 on 2023-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0020_linkbatch_cached_capture_job_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='manual_sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='registrar',
            name='manual_sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='name',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='name',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
