# Generated by Django 3.2.20 on 2023-08-30 16:21

from django.db import migrations, models

def backfill_uploaded_capture_software(apps, schema_editor):
    """
    Links whose `link.capture_job.superseded=True` are user uploads...
    but since old Perma links don't have related `CaptureJob`s,
    we need to look directly at each link's primary capture.

    Compare:
    https://github.com/harvard-lil/perma/commit/e0f0c1ed3aefa2c557243e4f9ade7ba776fa1e62#diff-a160e6e4a56d2c05a1f8f276c683537b41f96825025012112f68671e05b6d74aR9
    """
    Link = apps.get_model('perma', 'Link')
    print("Updating capture software for uploads.")
    Link.objects.filter(
        captures__user_upload=True
    ).update(
        captured_by_software='upload'
    )
    print("Updated capture software for uploads.")


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0021_auto_20230629_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='engine',
            field=models.CharField(choices=[('perma', 'perma'), ('scoop-api', 'scoop-api')], db_index=True, default='perma', max_length=255),
        ),
        migrations.AddField(
            model_name='historicallink',
            name='captured_by_software',
            field=models.CharField(db_index=True, default='perma', max_length=255),
        ),
        migrations.AddField(
            model_name='link',
            name='captured_by_software',
            field=models.CharField(db_index=True, default='perma', max_length=255),
        ),
        migrations.RunPython(backfill_uploaded_capture_software, migrations.RunPython.noop, elidable=True),
    ]
