# Generated by Django 3.2.20 on 2023-08-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0022_auto_20230830_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='scoop_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='scoop_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
