# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 18:57
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'perma', '0024_auto_20170602_1851'), (b'perma', '0025_auto_20170830_2026'), (b'perma', '0026_auto_20171002_1837'), (b'perma', '0027_auto_20171003_1854')]

    dependencies = [
        ('perma', '0023_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text=b'Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text=b'Whether this registrar qualifies for a free account.'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text=b'Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AddField(
            model_name='registrar',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text=b'Whether this registrar qualifies for a free account.'),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text=b"The last known status of registrar's paid subscription, from Perma Payments", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text=b"The last known status of registrar's paid subscription, from Perma Payments", max_length=50, null=True),
        ),
    ]
