# Generated by Django 3.2.20 on 2023-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0023_auto_20230830_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='scoop_logs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
