# Generated by Django 3.2.20 on 2023-08-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0024_capturejob_scoop_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='captured_by_browser',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='captured_by_browser',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
