# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 20:26
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0024_auto_20170602_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text=b'Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text=b'Whether this registrar qualifies for a free account.'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text=b'Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AddField(
            model_name='registrar',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text=b'Whether this registrar qualifies for a free account.'),
        ),
    ]
