# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0025_auto_20171012_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
