# Generated by Django 3.2.20 on 2023-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0025_auto_20230831_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='scoop_state',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
