# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0025_auto_20170830_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text=b"The last known status of registrar's paid subscription, from Perma Payments", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text=b"The last known status of registrar's paid subscription, from Perma Payments", max_length=20, null=True),
        ),
    ]
