# Generated by Django 3.2.20 on 2023-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0026_capturejob_scoop_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='role',
            field=models.CharField(choices=[('primary', 'primary'), ('screenshot', 'screenshot'), ('favicon', 'favicon'), ('provenance_summary', 'provenance_summary')], max_length=18),
        ),
    ]
