# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0026_auto_20171013_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='cached_paid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='cached_paid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
