# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0027_auto_20171116_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='shared_folder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_level_for_org', to='perma.Folder'),
        ),
    ]
