# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0028_auto_20171208_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='capturejob',
            name='submitted_url',
            field=models.CharField(blank=True, max_length=2100),
        ),
        migrations.AlterField(
            model_name='capturejob',
            name='status',
            field=models.CharField(choices=[(b'pending', b'pending'), (b'in_progress', b'in_progress'), (b'completed', b'completed'), (b'deleted', b'deleted'), (b'failed', b'failed'), (b'invalid', b'invalid')], db_index=True, default=b'pending', max_length=15),
        ),
        migrations.AddField(
            model_name='capturejob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perma.Batch'),
        ),
    ]
