# Generated by Django 3.2.23 on 2023-11-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0029_capturejob_scoop_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturejob',
            name='engine',
            field=models.CharField(choices=[('perma', 'perma'), ('scoop-api', 'scoop-api')], db_index=True, default='scoop-api', max_length=255),
        ),
    ]
