# Generated by Django 3.2.23 on 2023-12-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0030_alter_capturejob_engine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UncaughtError',
        ),
    ]
