# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0030_auto_20180430_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkbatch',
            options={'verbose_name_plural': 'link batches'},
        ),
        migrations.AlterField(
            model_name='linkbatch',
            name='started_on',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
