# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0030_auto_20180210_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturejob',
            name='link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capture_job', to='perma.Link'),
        ),
    ]
