# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def handle_linkless_capture_jobs(apps, schema_editor):
    """
    We cannot now recover who created invalid Capture Jobs. Assign them all to a dummy user.
    In dev/stage/prod, a special dummy user has been created for the purpose.
    Fall back to the first user (generally test_admin_user) locally, in the unlikely
    case developers have linkless capture jobs.
    """
    LinkUser = apps.get_model('perma', 'LinkUser')
    CaptureJob = apps.get_model('perma', 'CaptureJob')
    linkless_jobs = CaptureJob.objects.filter(link=None)
    default_user = LinkUser.objects.filter(email='orphaned_capture_jobs@perma.cc').first() or LinkUser.objects.first()
    if linkless_jobs:
        if default_user:
            for job in linkless_jobs:
                job.created_by = default_user
                job.save()
        else:
            raise Exception('There are linkless capture jobs, but no user is available to adopt them.')


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0031_auto_20180501_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capture_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            'UPDATE perma_capturejob c JOIN perma_link l ON c.link_id=l.guid SET c.created_by_id=l.created_by_id',
            migrations.RunSQL.noop
        ),
        migrations.RunPython(handle_linkless_capture_jobs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='capturejob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
