# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0031_auto_20180211_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='saved_folder',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, to='perma.Folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capturejob',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capture_jobs', to='perma.Batch'),
        ),
    ]
