# Generated by Django 4.2.8 on 2023-12-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0032_alter_genericstringtaggeditem_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalregistrar',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='historicalregistrar',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='historicalregistrar',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='historicalregistrar',
            name='partner_display_name',
        ),
        migrations.RemoveField(
            model_name='historicalregistrar',
            name='show_partner_status',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='partner_display_name',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='show_partner_status',
        ),
    ]
