# Generated by Django 4.2.8 on 2023-12-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0033_remove_historicalregistrar_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallink',
            name='thumbnail_status',
        ),
        migrations.RemoveField(
            model_name='link',
            name='thumbnail_status',
        ),
    ]
