# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0034_auto_20180625_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalregistrar',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text="The last known status of customer's paid subscription, from Perma Payments", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text="The last known status of customer's paid subscription, from Perma Payments", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text='Whether this customer qualifies for a free account.'),
        ),
    ]
