# Generated by Django 4.2.8 on 2023-12-11 20:13

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0034_remove_historicallink_thumbnail_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(models.F('user_deleted'), django.db.models.functions.datetime.TruncDate('creation_timestamp'), models.F('is_private'), models.F('is_unlisted'), models.F('cached_can_play_back'), name='ia_eligible_for_date_idx'),
        ),
    ]
