# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-27 16:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0035_auto_20180824_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='cached_paid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text="The last known status of customer's paid subscription, from Perma Payments", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='cached_paid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='cached_subscription_status',
            field=models.CharField(blank=True, help_text="The last known status of customer's paid subscription, from Perma Payments", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='nonpaying',
            field=models.BooleanField(default=True, help_text='Whether this customer qualifies for a free account.'),
        ),
    ]
