# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


def handle_premium_users(apps, schema_editor):
    """
    All LinkUsers who are currently paying belong to the "unlimited" tier:
    self.is_unlimited should be True
    """
    LinkUser = apps.get_model('perma', 'LinkUser')
    premium_users = LinkUser.objects.filter(nonpaying=False)
    for user in premium_users:
        user.unlimited = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0037_auto_20181004_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallinkuser',
            old_name='monthly_link_limit',
            new_name='link_limit',
        ),
        migrations.RenameField(
            model_name='linkuser',
            old_name='monthly_link_limit',
            new_name='link_limit',
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='link_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='link_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='registrar',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='registrar',
            name='unlimited',
            field=models.BooleanField(default=True, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.RunPython(handle_premium_users, migrations.RunPython.noop),
    ]
