# Generated by Django 4.2.11 on 2024-03-18 21:02

from django.db import migrations

FLAG_NAME = "vue-dashboard"


def create_vue_feature_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flag = Flag(
        name=FLAG_NAME,
        testing=True
    )
    flag.save()


def delete_vue_feature_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flags = Flag.objects.filter(name=FLAG_NAME)
    flags.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0037_historicallinkuser_is_superuser_linkuser_groups_and_more'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(create_vue_feature_flag, delete_vue_feature_flag),
    ]
