# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 21:41
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0037_auto_20181004_1709'),
    ]

    operations = [
        # Link Limit
        migrations.RenameField(
            model_name='historicallinkuser',
            old_name='monthly_link_limit',
            new_name='link_limit',
        ),
        migrations.RenameField(
            model_name='linkuser',
            old_name='monthly_link_limit',
            new_name='link_limit',
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='link_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='registrar',
            name='link_limit',
            field=models.IntegerField(default=10),
        ),
        # Link Limit Period, with everybody at `once`
        migrations.AddField(
            model_name='historicallinkuser',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        migrations.AddField(
            model_name='registrar',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        # Special handling for letting users create unlimited links
        migrations.AddField(
            model_name='historicalregistrar',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.AddField(
            model_name='historicallinkuser',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='unlimited',
            field=models.BooleanField(default=True, help_text='If unlimited, link_limit and related fields are ignored.'),
        ),
        # Monthly Rate to Base Rate; New Default Values
        migrations.RenameField(
            model_name='historicallinkuser',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.RenameField(
            model_name='historicalregistrar',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.RenameField(
            model_name='linkuser',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.AlterField(
            model_name='historicallinkuser',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Base rate for calculating subscription cost.', max_digits=19),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Base rate for calculating subscription cost.', max_digits=19),
        ),
        # Most everything switches to potentially paying;
        # Current registrars stay nonpaying by default, so no change present here.
        migrations.AlterField(
            model_name='historicallinkuser',
            name='nonpaying',
            field=models.BooleanField(default=False, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='nonpaying',
            field=models.BooleanField(default=False, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='nonpaying',
            field=models.BooleanField(default=False, help_text='Whether this customer qualifies for a free account.'),
        )
    ]
