# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0038_auto_20181115_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallinkuser',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.RenameField(
            model_name='historicalregistrar',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.RenameField(
            model_name='linkuser',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
        migrations.RenameField(
            model_name='registrar',
            old_name='monthly_rate',
            new_name='base_rate',
        ),
    ]
