# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0039_users_to_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='cached_subscription_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Local record of what the customer last paid.', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='cached_subscription_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Local record of what the customer last paid.', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='cached_subscription_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Local record of what the customer last paid.', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='registrar',
            name='cached_subscription_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Local record of what the customer last paid.', max_digits=19, null=True),
        ),
    ]
