# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0040_auto_20181210_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='in_trial',
            field=models.BooleanField(default=True, help_text='Is this customer in their trial period?'),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='in_trial',
            field=models.BooleanField(default=True, help_text='Is this customer in their trial period?'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='in_trial',
            field=models.BooleanField(default=True, help_text='Is this customer in their trial period?'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='in_trial',
            field=models.BooleanField(default=True, help_text='Is this customer in their trial period?'),
        ),
    ]
