# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0040_auto_20181210_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinkuser',
            name='bonus_links_remaining',
            field=models.IntegerField(default=0, help_text='A mechanism for giving a customer extra links, without affecting their long-term link_limit or link_limit_period.'),
        ),
        migrations.AddField(
            model_name='historicalregistrar',
            name='bonus_links_remaining',
            field=models.IntegerField(default=0, help_text='A mechanism for giving a customer extra links, without affecting their long-term link_limit or link_limit_period.'),
        ),
        migrations.AddField(
            model_name='linkuser',
            name='bonus_links_remaining',
            field=models.IntegerField(default=0, help_text='A mechanism for giving a customer extra links, without affecting their long-term link_limit or link_limit_period.'),
        ),
        migrations.AddField(
            model_name='registrar',
            name='bonus_links_remaining',
            field=models.IntegerField(default=0, help_text='A mechanism for giving a customer extra links, without affecting their long-term link_limit or link_limit_period.'),
        ),
    ]
