# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 19:19
from __future__ import unicode_literals

from django.db import migrations, models


def handle_existing_users(apps, schema_editor):
    """
    All users should have the option to purchase a personal subscription.
    We can manually adjust any exceptions.
    """
    LinkUser = apps.get_model('perma', 'LinkUser')
    nonpaying_users = LinkUser.objects.filter(nonpaying=True)
    for user in nonpaying_users:
        user.nonpaying = False
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0040_auto_20181204_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinkuser',
            name='nonpaying',
            field=models.BooleanField(default=False, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='nonpaying',
            field=models.BooleanField(default=False, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='nonpaying',
            field=models.BooleanField(default=False, help_text='Whether this customer qualifies for a free account.'),
        ),
        migrations.RunPython(handle_existing_users, migrations.RunPython.noop)
    ]
