# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 16:52
from __future__ import unicode_literals

from django.db import migrations


def grant_ten_bonus_links(apps, schema_editor):
    """
    All active LinkUsers should be awarded 10 bonus links
    """
    LinkUser = apps.get_model('perma', 'LinkUser')
    active_users = LinkUser.objects.filter(is_confirmed=True, is_active=True)
    active_users.update(bonus_links_remaining=10)


def zero_out_bonus_links(apps, schema_editor):
    LinkUser = apps.get_model('perma', 'LinkUser')
    active_users = LinkUser.objects.filter(is_confirmed=True, is_active=True)
    active_users.update(bonus_links_remaining=0)


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0041_auto_20190107_1447'),
    ]

    operations = [
        migrations.RunPython(grant_ten_bonus_links, zero_out_bonus_links),
    ]
