# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0041_auto_20181205_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinkuser',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='link_limit_period',
            field=models.CharField(choices=[('once', 'once'), ('monthly', 'monthly'), ('annually', 'annually')], default='once', max_length=8),
        ),
    ]
