# Generated by Django 4.2.13 on 2024-05-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0041_folder_tree_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='level',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='perma.folder', verbose_name='parent'),
        ),
    ]
