# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0042_handle_trials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallink',
            name='replacement_link',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='New link to which readers should be forwarded when trying to view this link.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='perma.Link'),
        ),
        migrations.AlterField(
            model_name='historicallinkuser',
            name='registrar',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set, this user is a registrar user. This should not be set if org is set!', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='perma.Registrar'),
        ),
    ]
