# Generated by Django 4.2.13 on 2024-06-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0042_remove_folder_level_remove_folder_lft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='historicallink',
            name='wacz_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='wacz_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
