# Generated by Django 4.2.14 on 2024-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0044_auto_20240701_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('screenshot', 'Screenshot'), ('favicon', 'Favicon'), ('provenance_summary', 'Provenance Summary'), ('pdf_snapshot', 'PDF Snapshot'), ('dom_snapshot', 'DOM Snapshot'), ('video_summary', 'Video Summary')], max_length=18),
        ),
    ]
