# Generated by Django 4.2.14 on 2024-07-18 21:30

import django.contrib.postgres.fields
from django.db import migrations, models
import perma.models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0045_alter_capture_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='archive_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('warc', 'warc'), ('wacz', 'wacz')], max_length=15), default=perma.models.get_default_archive_formats, size=None),
        ),
    ]
