# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-14 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0045_auto_20190415_1556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CDXLine',
        ),
    ]
