# Generated by Django 4.2.14 on 2024-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perma", "0046_capturejob_archive_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorship",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
