# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 20:52
from __future__ import unicode_literals

from django.db import migrations
import surt


def populate_surt(apps, schema_editor):
    Link = apps.get_model('perma', 'Link')
    HistoricalLink = apps.get_model('perma', 'HistoricalLink')

    # This syntax isn't available until Django 2.2.
    # Will this migration be too slow? If yes, I can upgrade Django now.
    #
    # links = []
    # for link in Link.objects.all():
    #     link.submitted_url_surt = surt.surt(link.submitted_url)
    #     links.append(link)
    # Link.objects.bulk_update(links, ['submitted_url_surt'])

    for link in Link.objects.all():
        link.submitted_url_surt = surt.surt(link.submitted_url)
        link.save()

    for link in HistoricalLink.objects.all():
        link.submitted_url_surt = surt.surt(link.submitted_url)
        link.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0047_auto_20200127_2049'),
    ]

    operations = [
        migrations.RunPython(populate_surt, migrations.operations.RunPython.noop),
    ]
