# Generated by Django 4.2.14 on 2024-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0047_sponsorship_expires_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['status', 'expires_at'], name='perma_spons_status_b5a883_idx'),
        ),
    ]
