# Generated by Django 2.2.10 on 2020-02-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0047_auto_20200204_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='superseded',
            field=models.BooleanField(default=False, help_text='A user upload has made this CaptureJob irrelevant to the playback of its related Link'),
        ),
        migrations.AddField(
            model_name='historicallink',
            name='cached_can_play_back',
            field=models.BooleanField(default=None, help_text='After archive_timestamp, cache whether this link can be played back, for efficiency.', null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_can_play_back',
            field=models.BooleanField(default=None, help_text='After archive_timestamp, cache whether this link can be played back, for efficiency.', null=True),
        ),
    ]
