# Generated by Django 4.2.15 on 2024-08-29 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0048_sponsorship_perma_spons_status_b5a883_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganizationAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perma.organization')),
                ('user', models.ForeignKey(db_column='linkuser_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perma_linkuser_organizations',
            },
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If set, this user is an org user. This should not be set if registrar is set!<br><br>Note: <b>This list will include deleted orgs of which this user is a member.</b> This is a historical record and deleted org memberships cannot be removed.<br><br>', related_name='users', through='perma.UserOrganizationAffiliation', to='perma.organization'),
        ),
    ]
