# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0048_auto_20200127_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallink',
            name='submitted_url_surt',
            field=models.CharField(max_length=4200),
        ),
        migrations.AlterField(
            model_name='link',
            name='submitted_url_surt',
            field=models.CharField(max_length=4200),
        ),
    ]
