# Generated by Django 2.2.10 on 2020-02-18 20:36

from django.db import migrations

import logging
logger = logging.getLogger(__name__)


def mark_capture_jobs_superseded(apps, schema_editor):
    Capture = apps.get_model('perma', 'Capture')
    CaptureJob = apps.get_model('perma', 'CaptureJob')
    updated = CaptureJob.objects.filter(
        link__guid__in=Capture.objects.filter(user_upload=True).select_related('link').values_list('link__guid', flat=True)
    ).update(
        superseded=True
    )
    logger.info(f"Updated {updated} CaptureJobs")


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0048_auto_20200218_2033'),
    ]

    operations = [
        migrations.RunPython(mark_capture_jobs_superseded, migrations.RunPython.noop),
    ]
