# Generated by Django 4.2.16 on 2024-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0049_userorganizationaffiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizationaffiliation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userorganizationaffiliation',
            index=models.Index(fields=['expires_at'], name='perma_linku_expires_9e339b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userorganizationaffiliation',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_affiliation'),
        ),
    ]
