# Generated by Django 4.2.15 on 2024-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0049_userorganizationaffiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizationaffiliation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
