# Generated by Django 4.2.16 on 2024-10-30 17:32

from django.db import migrations

FLAG_NAME = "wacz-playback"

def toggle_wacz_playback_feature_flag_on(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flag = Flag.objects.get(name=FLAG_NAME)
    flag.everyone = True
    flag.save()


def toggle_wacz_playback_feature_flag_off(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flag = Flag.objects.get(name=FLAG_NAME)
    flag.everyone = False
    flag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0050_userorganizationaffiliation_expires_at_and_more'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(toggle_wacz_playback_feature_flag_on, toggle_wacz_playback_feature_flag_off),
    ]
