# Generated by Django 4.2.16 on 2024-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0051_auto_20241030_1732'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='perma_link_creatio_be33de_idx',
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['creation_timestamp', 'guid'], name='perma_link_creatio_958ed0_idx'),
        ),
    ]
