# Generated by Django 4.2.16 on 2024-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0051_auto_20241030_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinkuser',
            name='bonus_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='bonus_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='bonus_links',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='bonus_links',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
