# Generated by Django 2.2.10 on 2020-02-26 16:31

from django.db import migrations


import logging
logger = logging.getLogger(__name__)


def mark_deleted_links_unplayable(apps, schema_editor):
    # In data migrations, custom managers like all_with_deleted and the inverse are not available: 
    # here, a standard filter works.
    Link = apps.get_model('perma', 'Link')
    user_deleted = Link.objects.filter(user_deleted=True).update(cached_can_play_back=False)
    logger.info(f"Updated {user_deleted} Links")

def null_cached_can_play_back(apps, schema_editor):
    # In data migrations, custom managers like all_with_deleted and the inverse are not available: 
    # here, a standard filter works.
    Link = apps.get_model('perma', 'Link')
    user_deleted = Link.objects.filter(user_deleted=True).update(cached_can_play_back=None)
    logger.info(f"Updated {user_deleted} Links")

class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0052_auto_20200224_1949'),
    ]

    operations = [
        migrations.RunPython(mark_deleted_links_unplayable, null_cached_can_play_back),
    ]
