# Generated by Django 4.2.16 on 2024-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0052_remove_link_perma_link_creatio_be33de_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['-creation_timestamp', 'guid'], name='perma_link_creatio_ef2767_idx'),
        ),
    ]
