# Generated by Django 2.2.10 on 2020-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0053_auto_20200226_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallink',
            name='cached_can_play_back',
            field=models.BooleanField(db_index=True, default=None, help_text='After archive_timestamp, cache whether this link can be played back, for efficiency.', null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='cached_can_play_back',
            field=models.BooleanField(db_index=True, default=None, help_text='After archive_timestamp, cache whether this link can be played back, for efficiency.', null=True),
        ),
    ]
