# Generated by Django 4.2.16 on 2024-10-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0053_link_perma_link_creatio_ef2767_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='capturejob',
            index=models.Index(fields=['capture_start_time'], name='perma_captu_capture_daadd2_idx'),
        ),
    ]
