# Generated by Django 4.2.16 on 2024-11-14 17:03

from django.db import migrations

FLAG_NAME = "wacz-playback"

def delete_wacz_playback_feature_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flags = Flag.objects.filter(name=FLAG_NAME)
    flags.delete()

def create_wacz_playback_feature_flag(apps, schema_editor):
    Flag = apps.get_model("waffle", "Flag")
    flag = Flag(
        name=FLAG_NAME,
        testing=True
    )
    flag.save()

class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0054_capturejob_perma_captu_capture_daadd2_idx'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(
            delete_wacz_playback_feature_flag,
            create_wacz_playback_feature_flag,
        ),
    ]
