# Generated by Django 2.2.10 on 2020-03-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0054_auto_20200304_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallink',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('completed', 'completed'), ('failed', 'failed'), ('deleted', 'deleted'), ('deletion_incomplete', 'deletion_incomplete')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='link',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('completed', 'completed'), ('failed', 'failed'), ('deleted', 'deleted'), ('deletion_incomplete', 'deletion_incomplete')], db_index=True, default='not_started', max_length=20),
        ),
    ]
