# Generated by Django 2.2.10 on 2020-03-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0055_auto_20200304_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallink',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('completed', 'completed'), ('failed', 'failed'), ('deleted', 'deleted'), ('deletion_incomplete', 'deletion_incomplete'), ('deletion_required', 'deletion_required'), ('upload_or_reupload_required', 'upload_or_reupload_required')], db_index=True, default='not_started', max_length=28),
        ),
        migrations.AlterField(
            model_name='link',
            name='internet_archive_upload_status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('completed', 'completed'), ('failed', 'failed'), ('deleted', 'deleted'), ('deletion_incomplete', 'deletion_incomplete'), ('deletion_required', 'deletion_required'), ('upload_or_reupload_required', 'upload_or_reupload_required')], db_index=True, default='not_started', max_length=28),
        ),
    ]
