# Generated by Django 4.2.20 on 2025-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0057_auto_20241120_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturejob',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
