# Generated by Django 4.2.20 on 2025-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0058_capturejob_creation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturejob',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
