# Generated by Django 2.2.13 on 2020-06-18 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0059_auto_20200513_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstringtaggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perma_genericstringtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
