# Generated by Django 4.2.23 on 2026-06-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0064_alter_link_internet_archive_upload_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetarchiveitem',
            old_name='complete',
            new_name='initial_uploads_complete',
        ),
        migrations.AlterField(
            model_name='internetarchiveitem',
            name='initial_uploads_complete',
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True when a daily upload task has found zero eligible links for this calendar day "
                    "that lack an InternetArchiveFile. Only set after the IA Item is older than yesterday, "
                    "to avoid missing any links. The daily upload scheduler skips days marked True. "
                    "This field does not consider whether the day's IA Item lacks links due to later "
                    "eligibility changes, such as changes in links' privacy."
                ),
                verbose_name='Initial uploads complete',
            ),
        ),
    ]
