# Generated by Django 2.2.22 on 2021-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0064_folder_cached_path'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user_deleted', 'is_private', 'is_unlisted'], name='perma_link_user_de_25ae38_idx'),
        ),
    ]
