# Generated by Django 2.2.22 on 2021-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0066_auto_20210520_1650'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='perma_link_user_de_25ae38_idx',
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['user_deleted', 'is_private', 'is_unlisted', 'cached_can_play_back', 'internet_archive_upload_status'], name='perma_link_user_de_b6e6a5_idx'),
        ),
    ]
