# Generated by Django 4.2.23 on 2026-07-14 19:33

from django.db import migrations

MESSAGE_SWITCH_NAME = "display_cybersource_freeze_message"
FREEZE_SWITCH_NAME = "freeze_cybersource_transactions"

def create_switch(apps, switch_name):
    Switch = apps.get_model("waffle", "Switch")
    switch = Switch(
        name=switch_name,
        active=False
    )
    switch.save()

def delete_switch(apps, switch_name):
    Switch = apps.get_model("waffle", "Switch")
    switches = Switch.objects.filter(name=switch_name)
    switches.delete()

def create_message_switch(apps, schema_editor):
    create_switch(apps, MESSAGE_SWITCH_NAME)

def delete_message_switch(apps, schema_editor):
    delete_switch(apps, MESSAGE_SWITCH_NAME)

def create_freeze_switch(apps, schema_editor):
    create_switch(apps, FREEZE_SWITCH_NAME)

def delete_freeze_switch(apps, schema_editor):
    delete_switch(apps, FREEZE_SWITCH_NAME)


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0067_alter_historicalregistrar_international_and_more'),
        ('waffle', '0004_update_everyone_nullbooleanfield'),
    ]

    operations = [
        migrations.RunPython(create_message_switch, delete_message_switch),
        migrations.RunPython(create_freeze_switch, delete_freeze_switch),
    ]
