# Generated by Django 2.2.22 on 2021-05-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0068_delete_historicallink'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "SET foreign_key_checks = 0;",
                "DROP TABLE IF EXISTS `celery_taskmeta`, `celery_tasksetmeta`, `djcelery_crontabschedule`, `djcelery_intervalschedule`, `djcelery_periodictask`, `djcelery_periodictasks`, `djcelery_taskstate`, `djcelery_workerstate`, `perma_asset`, `south_migrationhistory`, `tastypie_apiaccess`, `tastypie_apikey`, `thumbnail_kvstore` CASCADE;",
                "SET foreign_key_checks = 1;"
            ],
            reverse_sql=migrations.RunSQL.noop,
            elidable=True
        ),
    ]
