# Generated by Django 5.2.17 on 2026-08-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0075_remove_historicallinkuser_grandfathered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallinkuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User', 'verbose_name_plural': 'historical Users'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organization', 'verbose_name_plural': 'historical organizations'},
        ),
        migrations.AlterModelOptions(
            name='historicalregistrar',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical registrar', 'verbose_name_plural': 'historical registrars'},
        ),
        migrations.AlterField(
            model_name='historicallinkuser',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorganization',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalregistrar',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='linkuser',
            name='sponsoring_registrars',
            field=models.ManyToManyField(blank=True, help_text='If set, this user is sponsored by a registrar. Any user can be sponsored by any registrar.', related_name='sponsored_users', through='perma.Sponsorship', through_fields=('user', 'registrar'), to='perma.registrar'),
        ),
    ]
