# Generated by Django 4.2.23 on 2026-09-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0065_rename_internetarchiveitem_complete'),
        ('perma', '0075_remove_historicallinkuser_grandfathered_and_more'),
    ]

    operations = []
