# Generated by Django 4.2.23 on 2026-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0077_axes_session_hash_database_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrar',
            name='sponsored_link_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrar',
            name='sponsored_link_count',
            field=models.IntegerField(default=0),
        ),
    ]
