# Generated by Django 5.2.17 on 2026-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0078_captureattemptfacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetarchivefile',
            name='status_updated',
            field=models.DateTimeField(blank=True, help_text="When status was last saved, even if unchanged: an upload retry saves 'upload_attempted' again.", null=True),
        ),
        migrations.AddField(
            model_name='internetarchiveitem',
            name='next_confirmation_check',
            field=models.DateTimeField(blank=True, help_text='Uploads to this item awaiting confirmation are not checked again before this time.', null=True),
        ),
        migrations.AlterField(
            model_name='internetarchivefile',
            name='status',
            field=models.CharField(blank=True, choices=[('upload_attempted', 'upload_attempted'), ('upload_submitted', 'upload_submitted'), ('upload_unconfirmed', 'upload_unconfirmed'), ('confirmed_present', 'confirmed_present'), ('deletion_attempted', 'deletion_attempted'), ('deletion_submitted', 'deletion_submitted'), ('confirmed_absent', 'confirmed_absent')], db_index=True, help_text='upload_unconfirmed: IA accepted the upload, but the file did not appear with the expected metadata within INTERNET_ARCHIVE_UPLOAD_CONFIRMATION_MAX_AGE, so we stopped checking. Needs a human.', max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='internetarchiveitem',
            name='tasks_in_progress',
            field=models.IntegerField(db_index=True, default=0, help_text='We have asked Internet Archive to run appx this many tasks for this item and have not yet confirmed that those tasks are complete; derivative tasks not counted. Recomputed from file statuses by refresh_tasks_in_progress.'),
        ),
    ]
