# Generated by Django 5.2.17 on 2026-09-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perma', '0081_link_autovacuum_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetarchivefile',
            name='status_updated',
            field=models.DateTimeField(blank=True, help_text="When status was last saved, even if unchanged: an upload retry saves 'upload_attempted' again.", null=True),
        ),
        migrations.AddField(
            model_name='internetarchivefile',
            name='attempts',
            field=models.IntegerField(db_default=0, default=0, help_text="How many times the current upload or deletion has been started: 1 when it begins, plus 1 each time it is taken up again after going stale. A task's own retries are not counted."),
        ),
        migrations.AddField(
            model_name='internetarchiveitem',
            name='next_confirmation_check',
            field=models.DateTimeField(blank=True, help_text='Uploads to this item awaiting confirmation are not checked again before this time.', null=True),
        ),
        migrations.AlterField(
            model_name='internetarchivefile',
            name='status',
            field=models.CharField(blank=True, choices=[('upload_attempted', 'upload_attempted'), ('upload_submitted', 'upload_submitted'), ('upload_unconfirmed', 'upload_unconfirmed'), ('upload_failed', 'upload_failed'), ('confirmed_present', 'confirmed_present'), ('deletion_attempted', 'deletion_attempted'), ('deletion_submitted', 'deletion_submitted'), ('deletion_unconfirmed', 'deletion_unconfirmed'), ('deletion_failed', 'deletion_failed'), ('confirmed_absent', 'confirmed_absent')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internetarchiveitem',
            name='tasks_in_progress',
            field=models.IntegerField(db_index=True, default=0, help_text='We have asked Internet Archive to run appx this many tasks for this item and have not yet confirmed that those tasks are complete; derivative tasks not counted. Recomputed from file statuses by refresh_tasks_in_progress.'),
        ),
    ]
